/* CVS $Id: $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/wymiwyg-commons-jena/src/org/wymiwyg/commons/vocabulary/atom.rdf
 *
 * @author Auto-generated by schemagen on 31 Mai 2007 01:33
 * @version $Id: $Id
 */
public class ATOM {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/";
    
/**
 * <p>The namespace of the vocabulary as a string</p>
 *
 *  @see #NS
 * @return a {@link java.lang.String} object.
 */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property representation = m_model.createProperty( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#representation" );
/** Constant <code>representation</code> */
    
    public static final Property content = m_model.createProperty( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#content" );
/** Constant <code>content</code> */
    
    public static final Property title = m_model.createProperty( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#title" );
/** Constant <code>title</code> */
    
    /** <p>An atom content</p> */
    public static final Resource Content = m_model.createResource( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#Content" );
    
    /** <p>An atom entry</p> */
    public static final Resource Entry = m_model.createResource( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#Entry" );
    
}
