/* CVS $Id: MEDIATYPES.java,v 1.1 2006/01/29 12:49:35 rebach Exp $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/wymiwyg-commons/src/org/wymiwyg/commons/vocabulary/mediatypes.rdf
 *
 * @author Auto-generated by schemagen on 27 Jan 2006 21:38
 * @version $Id: $Id
 */
public class MEDIATYPES {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://wymiwyg.org/ontologies/mediatypes#";
    
/**
 * <p>The namespace of the vocabulary as a string</p>
 *
 *  @see #NS
 * @return a {@link java.lang.String} object.
 */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>the canonical (or prefferred) mime-type for this Type</p> */
    public static final Property canonicalMimeType = m_model.createProperty( "http://wymiwyg.org/ontologies/mediatypes#canonicalMimeType" );
    
    /** <p>A mime-type for this Type</p> */
    public static final Property mimeType = m_model.createProperty( "http://wymiwyg.org/ontologies/mediatypes#mimeType" );
    
    /** <p>the canonical (or prefferred) file-extension for this Type</p> */
    public static final Property canonicalFileExtension = m_model.createProperty( "http://wymiwyg.org/ontologies/mediatypes#canonicalFileExtension" );
    
    /** <p>A file-extension for this Type</p> */
    public static final Property fileExtension = m_model.createProperty( "http://wymiwyg.org/ontologies/mediatypes#fileExtension" );
    
    /** <p>A media type. The thing denoted by a MIME media-type</p> */
    public static final Resource Type = m_model.createResource( "http://wymiwyg.org/ontologies/mediatypes#Type" );
    
    /** <p>A DAV compliant collection-resource according to RFC 2518</p> */
    public static final Resource Collection = m_model.createResource( "http://wymiwyg.org/ontologies/mediatypes#Collection" );
    
}
