/* CVS $Id: $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/wymiwyg-commons-jena/src/org/wymiwyg/commons/vocabulary/webdav.rdf
 *
 * @author Auto-generated by schemagen on 31 Mai 2007 01:33
 * @version $Id: $Id
 */
public class WEBDAV {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://wymiwyg.org/ontologies/webdav#";
    
/**
 * <p>The namespace of the vocabulary as a string</p>
 *
 *  @see #NS
 * @return a {@link java.lang.String} object.
 */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>point to a member of the collection</p> */
    public static final Property member = m_model.createProperty( "http://wymiwyg.org/ontologies/webdav#member" );
    
    /** <p>A DAV compliant collection-resource according to RFC 2518</p> */
    public static final Resource Collection = m_model.createResource( "http://wymiwyg.org/ontologies/webdav#Collection" );
    
    /** <p>A DAV compliant resource according to RFC 2518</p> */
    public static final Resource Resource = m_model.createResource( "http://wymiwyg.org/ontologies/webdav#Resource" );
    
}
