/* CVS $Id: $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/wymiwyg-commons-jena/src/org/wymiwyg/commons/vocabulary/atom.rdf 
 * @author Auto-generated by schemagen on 10 Feb 2007 21:54 
 */
public class ATOM {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property representation = m_model.createProperty( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#representation" );
    
    public static final Property content = m_model.createProperty( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#content" );
    
    public static final Property title = m_model.createProperty( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#title" );
    
    /** <p>An atom content</p> */
    public static final Resource Content = m_model.createResource( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#Content" );
    
    /** <p>An atom entry</p> */
    public static final Resource Entry = m_model.createResource( "https://bloged.dev.java.net/Ontologies/Atom/2005-01-03/#Entry" );
    
}
