/* CVS $Id: $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/wymiwyg-commons-jena/src/org/wymiwyg/commons/vocabulary/mod_content.rdf 
 * @author Auto-generated by schemagen on 10 Feb 2007 21:54 
 */
public class CONTENT {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/rss/1.0/modules/content/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>DRAFT: Not yet approved by WG. An element whose contents are the entity-encoded 
     *  or CDATA-escaped version of the content of the item.</p>
     */
    public static final Property encoded = m_model.createProperty( "http://purl.org/rss/1.0/modules/content/encoded" );
    
    /** <p>A on literal resource that indicates the encoding of the content:item. An 
     *  encoding is a reversable method of including content within the RSS file.</p>
     */
    public static final Property encoding = m_model.createProperty( "http://purl.org/rss/1.0/modules/content/encoding" );
    
    /** <p>The format of an item. Suggested best practice is to use the list of RDDL 
     *  natures.</p>
     */
    public static final Property format = m_model.createProperty( "http://purl.org/rss/1.0/modules/content/format" );
    
    /** <p>A sub-element of an RSS item or channel. Points to a list of content:item 
     *  elements.</p>
     */
    public static final Property items = m_model.createProperty( "http://purl.org/rss/1.0/modules/content/items" );
    
    /** <p>Describes a single version of the content for its parent item. If the content 
     *  is available on the Web at a specific address, content:item has an rdf:about 
     *  attribute containg the URI of the content.</p>
     */
    public static final Resource item = m_model.createResource( "http://purl.org/rss/1.0/modules/content/item" );
    
}
