/* CVS $Id$ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from http://discobits.org/ontology.en.de.fr.it.rdf 
 * @author Auto-generated by schemagen on 14 Sep 2006 22:22 
 */
public class DISCOBITS {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://discobits.org/ontology#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty contained = m_model.createObjectProperty( "http://discobits.org/ontology#contained" );
    
    public static final ObjectProperty representedProperty = m_model.createObjectProperty( "http://discobits.org/ontology#representedProperty" );
    
    public static final ObjectProperty components = m_model.createObjectProperty( "http://discobits.org/ontology#components" );
    
    public static final Property infoBit = m_model.createProperty( "http://discobits.org/ontology#infoBit" );
    
    public static final OntClass BinaryInfoDiscoBit = m_model.createClass( "http://discobits.org/ontology#BinaryInfoDiscoBit" );
    
    public static final OntClass ImageInfoDiscoBit = m_model.createClass( "http://discobits.org/ontology#ImageInfoDiscoBit" );
    
    public static final OntClass XHTMLInfoDiscoBit = m_model.createClass( "http://discobits.org/ontology#XHTMLInfoDiscoBit" );
    
    public static final OntClass InfoDiscoBit = m_model.createClass( "http://discobits.org/ontology#InfoDiscoBit" );
    
    public static final OntClass OrderedContent = m_model.createClass( "http://discobits.org/ontology#OrderedContent" );
    
    public static final OntClass TitledContent = m_model.createClass( "http://discobits.org/ontology#TitledContent" );
    
    public static final OntClass DiscoBit = m_model.createClass( "http://discobits.org/ontology#DiscoBit" );
    
    public static final OntClass AlternativeSet = m_model.createClass( "http://discobits.org/ontology#AlternativeSet" );
    
    public static final OntClass PositionedDiscoBit = m_model.createClass( "http://discobits.org/ontology#PositionedDiscoBit" );
    
    public static final OntClass GenericOrderedContent = m_model.createClass( "http://discobits.org/ontology#GenericOrderedContent" );
    
    public static final OntClass InfoBit = m_model.createClass( "http://discobits.org/ontology#InfoBit" );
    
}
