/* CVS $Id: FOAFEX.java,v 1.8 2005/12/20 20:54:11 rebach Exp $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /home/reto/workspace/wymiwyg-commons/src/org/wymiwyg/commons/vocabulary/foaf-extensions.rdf 
 * @author Auto-generated by schemagen on 20 Dez 2005 21:47 
 */
public class FOAFEX {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://wymiwyg.org/ontologies/foaf/extensions#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>inverse of foaf:knows</p> */
    public static final Property knownBy = m_model.createProperty( "http://wymiwyg.org/ontologies/foaf/extensions#knownBy" );
    
    /** <p>Indicates a document which has the subject as primary-topic</p> */
    public static final Property agentDescriptionDocument = m_model.createProperty( "http://wymiwyg.org/ontologies/foaf/extensions#agentDescriptionDocument" );
    
    /** <p>Indicates a document which has the subject as primary-topic and is a foaf:PersonalProfileDocument</p> */
    public static final Property personalProfileDocument = m_model.createProperty( "http://wymiwyg.org/ontologies/foaf/extensions#personalProfileDocument" );
    
    /** <p>A document with a foaf:Agent as foaf:primarySubject</p> */
    public static final Resource AgentProfileDocument = m_model.createResource( "http://wymiwyg.org/ontologies/foaf/extensions#AgentProfileDocument" );
    
}
