/* CVS $Id: GEOFEX.java,v 1.3 2006/03/22 16:11:20 rebach Exp $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from src/org/wymiwyg/commons/vocabulary/geof-extensions.rdf 
 * @author Auto-generated by schemagen on 22 Mar 2006 14:04 
 */
public class GEOFEX {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.RDFS_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://wymiwyg.org/ontologies/geof/extensions#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>A code for a SpatialThing, like a country or state-code</p> */
    public static final Property code = m_model.createProperty( "http://wymiwyg.org/ontologies/geof/extensions#code" );
    
    /** <p>A document with the subject as the space thing primarily related to it. This 
     *  is different than the primaryTopicOf as the latter could be a political institution 
     *  rather than a space-thing.</p>
     */
    public static final Property primarySpaceThingOf = m_model.createProperty( "http://wymiwyg.org/ontologies/geof/extensions#primarySpaceThingOf" );
    
}
