/* CVS $Id: INFOATOM.java,v 1.1 2006/02/15 18:31:25 rebach Exp $ */
package org.wymiwyg.commons.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*; 
/**
 * Vocabulary definitions from http://atomowl.org/ontologies/infoatom.de.fr.en.rdf 
 * @author Auto-generated by schemagen on 04 Feb 2006 16:31 
 */
public class INFOATOM {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://atomowl.org/ontologies/infoatom#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty target = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#target" );
    
    public static final ObjectProperty component = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#component" );
    
    public static final ObjectProperty invalid = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#invalid" );
    
    public static final ObjectProperty author = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#author" );
    
    public static final ObjectProperty contributor = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#contributor" );
    
    public static final ObjectProperty componentRoleType = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#componentRoleType" );
    
    public static final ObjectProperty componentRole = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#componentRole" );
    
    public static final ObjectProperty representation = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#representation" );
    
    public static final ObjectProperty inReplyTo = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#inReplyTo" );
    
    /** <p>A Relation of which the subject is the source.</p> */
    public static final ObjectProperty link = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#link" );
    
    public static final ObjectProperty source = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#source" );
    
    public static final ObjectProperty bytes = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#bytes" );
    
    public static final ObjectProperty isTranslationOf = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#isTranslationOf" );
    
    public static final ObjectProperty encoding = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#encoding" );
    
    public static final ObjectProperty valid = m_model.createObjectProperty( "http://atomowl.org/ontologies/infoatom#valid" );
    
    public static final DatatypeProperty mimeType = m_model.createDatatypeProperty( "http://atomowl.org/ontologies/infoatom#mimeType" );
    
    public static final OntClass EncodingSet = m_model.createClass( "http://atomowl.org/ontologies/infoatom#EncodingSet" );
    
    public static final OntClass InformationResource = m_model.createClass( "http://atomowl.org/ontologies/infoatom#InformationResource" );
    
    public static final OntClass Representation = m_model.createClass( "http://atomowl.org/ontologies/infoatom#Representation" );
    
    public static final OntClass Bytes = m_model.createClass( "http://atomowl.org/ontologies/infoatom#Bytes" );
    
    public static final OntClass Encoding = m_model.createClass( "http://atomowl.org/ontologies/infoatom#Encoding" );
    
    public static final OntClass LanguageSet = m_model.createClass( "http://atomowl.org/ontologies/infoatom#LanguageSet" );
    
    public static final OntClass RevisionHistory = m_model.createClass( "http://atomowl.org/ontologies/infoatom#RevisionHistory" );
    
    public static final OntClass Relation = m_model.createClass( "http://atomowl.org/ontologies/infoatom#Relation" );
    
    public static final OntClass ComponentRole = m_model.createClass( "http://atomowl.org/ontologies/infoatom#ComponentRole" );
    
}
